### ISSUE TITLE
一般用户禁止使用su

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/mpi-servers#1]
为了增强安全性，禁止一般用户使用su切换到其他用户。

**Comment by wulamao** [comment]
Later, I will try this method refer to https://www.thegeekdiary.com/how-to-restrict-su-access-to-a-user-only-by-pam/

**Comment by gqqnbig** [comment]
https://serverfault.com/questions/69216/disable-su-on-machine
我看好像设置
chmod o-x /bin/su
再把su的组设为wheel，管理员加入wheel组，就可以了。其他人不能运行su，wheel组的可以。

**Comment by wulamao** [comment]
故障记录： 注释了sudoers 文件中 %sudo ALL = (ALL) ALL, 导致sudo用户组组无法使用sudo命令。

**Comment by wulamao** [comment]
> 故障记录： 注释了sudoers 文件中 %sudo ALL = (ALL) ALL, 导致sudo用户组失去权限，无法使用sudo命令。

使用带有live USB功能的启动盘，进入U盘带的系统后挂载 /dev/mapper/ubuntu--vg-ubuntu--lv，然后修改sudoers文件。

**Comment by gqqnbig** [comment]
```bash
16:01:22 qiqig@eureka:~$ ls -l  /usr/bin/su
-rwsr-xr-- 1 root wheel 67816 Jul 21  2020 /usr/bin/su
16:01:42 qiqig@eureka:~$ su qiqitest
Password:
qiqitest@eureka:/home/qiqig$ getent group wheel
wheel:x:1123:qiqig,will,root
qiqitest@eureka:/home/qiqig$ su qiqig
bash: /usr/bin/su: Permission denied
```

`su`的所有权需要为root:wheel，mod为4754。这种情况下，qiqig在wheel组，可以运行su。qiqitest不在wheel组，不能运行su。

**Comment by gqqnbig** [comment]
https://github.com/gqqnbig/mpi-servers/wiki/公共配置

在安全设置部分，请测试一下

**Comment by wulamao** [comment]
> [https://github.com/gqqnbig/mpi-servers/wiki/公共配置](https://github.com/gqqnbig/mpi-servers/wiki/%E5%85%AC%E5%85%B1%E9%85%8D%E7%BD%AE)
> 
> 在安全设置部分，请测试一下
---
测试过程如下：
```bash
创建普通用户 will_test
(base) will_test@eureka:/home/will$ groups
will_test aptuser certificateLoginOnly
测试1：普通用户使用 su 命令
(base) will_test@eureka:/home/will$ su
bash: /usr/bin/su: Permission denied
测试2：普通用户使用 su 命令切换超级用户
(base) will_test@eureka:/home/will$ su root
bash: /usr/bin/su: Permission denied
测试3：普通用户使用  su 命令切其他用户
(base) will_test@eureka:/home/will$ su will
bash: /usr/bin/su: Permission denied
测试4：普通用户使用 sudo 命令
(base) will_test@eureka:/home/will$ sudo ls
[sudo] password for will_test: 
Sorry, user will_test is not allowed to execute '/usr/bin/ls' as root on eureka.
```
测试结果：一般用户无法使用su、sudo命令，测试通过。
