### ISSUE TITLE
NFS优化：支持备份和存储配额

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/mpi-servers#16]
# 现状与问题

目前home目录的结构如下：

用户gqqnbig有家目录/home/gqqnbig，其中有shared，是软链接，链接到/home/shared/gqqnbig。

/home/shared通过NFS共享。

/home挂载在btrfs文件系统。quota程序不支持btrfs。但是btrfs有自己的配额程序，就是对一个文件夹（subvolume）实施大小限制。目前，一个用户有两个文件夹（/home/gqqnbig和/home/shared/gqqnbig），btrfs的配额程序无法加总限制。

btrfs自带备份系统，它的备份比较高级，就是备份时做个镜像，速度极快，之后如果原文件改变，btrfs才把原文件复制一份到备份里，用专业术语说就是**写时复制**。

目前我们的目录结构也不太支持备份，同样是因为用户有两个文件夹。

# 解决办法需要满足的要求
Solutions should scale. O(n) solution is perhaps still too complex to me，比如有n个用户，配置文件里就要写n行。

最好允许逐步迁移，不要一下子影响所有用户。

# 可能的解决办法

一个用户只有一个家目录，如/home/gqqnbig。

/home通过NFS共享，挂载到/rhome，tentatively。rhome表示remote home，这样可以和本地用户相区别，并且现有用户不用立即迁移。

/home/gqqnbig/fast是个软链接，链接到/tmp/gqqnbig，tentatively。fast提供访问本地硬盘的方法。

这样一来，对每个用户，如/home/gqqnbig，btrfs对其实施备份和存储配额。btrfs无法排除fast软链接，但它仅仅是个链接，问题不大。

~里面dotfiles是配置文件，aha上可以用，eureka上不一定可以用。但是集群服务器都用ubuntu 20.04，虽然装的软件不太一样，但应该问题不大。

**Comment by gqqnbig** [comment]
Please advise

**Comment by gqqnbig** [comment]
Each quota group can be grouped into a parent qgroup so to share a common limit. https://btrfs.wiki.kernel.org/index.php/Quota_support

**Comment by gqqnbig** [comment]
https://unix.stackexchange.com/questions/149932/how-to-make-a-btrfs-snapshot-writable

**Comment by Lu-MPI** [comment]
资源的申请、限制和配额的好处是显而易见的。

但限制/配额的策略可能不容易制定。比如平均分配显然是不合理的，因为不同研究内容对资源的需求是不平均、不均衡的。

可能的需求例子：
- 数据挖掘：大量存储 + 大量CPU。
- 机器视觉：数据集 + 大量GPU。

因此，我认为可以先收集用户资源用量的信息。
在遇到资源瓶颈时，可以分析统计信息，并首先对占用过多的用户进行限制。

用户也应当有义务提升程序效率，充分利用资源。
用户也应当有义务对大量公共资源的占用进行说明。

**Comment by gqqnbig** [comment]
需要参考其他集群的做法。这里收集了一些集群 https://github.com/gqqnbig/mpi-servers/wiki/%E5%85%B6%E4%BB%96%E9%9B%86%E7%BE%A4

**Comment by gqqnbig** [comment]
Disks partitions may change. Revisit when /home used size is >50%.
