### ISSUE TITLE
Use Tatooine's 2T disk

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/mpi-servers#20]
Tatooine has a 2T disk unused.

There are a few options on how to use it.

## Option 1

Make aha:/home map to the 2T disk.

## Option 2
Make aha:/opt map to the 2T disk. 
Make eureka:/opt map to the same 2T disk.

## Option 3
Make aha:/backup map to the 2T disk.
nullify btrfs-backup-home.

## Option 4
Make aha:/home/$user/shared/.conda map to the 2T disk.

## Option 5
Mount the 2T disk to Tatooine:/tmp.
Note Eureka also has 1T disk unused, which may be mounted to Eureka:/tmp for consistency.

**Comment by Lu-MPI** [comment]
Suggest Option：

**NFS**. Use as a Local shared hard drive. Such as NFS for N41 office computer.

This is the fastest way to share files on a LAN. But I don’t know if any classmate need more space.

**Comment by gqqnbig** [comment]
save the disk for future use or GlusterFS.
