### ISSUE TITLE
Independent, more detailed user wiki

### ISSUE THREAD

**Issue by Lu-MPI** [gqqnbig/mpi-servers#21]
# 更显著的用户wiki

目前适用于管理员和用户的wiki是混合的，这可能导致用户迷路。
虽然wiki第一句就有说明，但目前用户须知的特性越来越多，这给wiki维护带来了一些挑战。

可行的方案如：
1.  管理员页面也添加前缀（右侧目录就可以明确区分）
2.  用户/管理员其一使用Home页内容做导航（右侧目录只有一个角色使用，另一个角色使用home页导航）
3. 建立两个wiki

# 更入门的用户wiki

目前的用户wiki假设了用户有一定的背景知识，这提高的阅读门槛使理解编写者的意图更困难。
我认为更详细的功能说明是有必要的，基于零背景知识的wiki是有必要的。

我已经开始在闲暇时间进行一些周边功能的说明，在[这里](https://github.com/Lu-MPI/MPI-Server-Note/wiki)。
如果允许的话，我可以参与到核心用户wiki的迭代中。

**Comment by gqqnbig** [comment]
我把你的wiki链接加进 https://github.com/gqqnbig/mpi-servers/wiki 了。
