### ISSUE TITLE
使用srun运行脚本，一段时间后，作业被意外取消

### ISSUE THREAD

**Issue by wulamao** [gqqnbig/mpi-servers#4]
运行服务器：eureka
错误提示：slurmstepd-localhost: error: *** STEP 204.0 ON localhost CANCELLED
问题描述：srun -o out.log python demo.py & 大概数个小时后作业意外终止
测试脚本如下：
```python
import datetime
import time

if __name__ == '__main__':
    while True:
        str = datetime.datetime.fromtimestamp(time.time())
        time.sleep(1)
        print(str)
```
out.log 内容如下：
```bash
2021-02-13 10:15:59.014811
2021-02-13 10:16:00.015876
... ...
2021-02-13 16:36:03.027407
slurmstepd-localhost: error: *** STEP 204.0 ON localhost CANCELLED AT 2021-02-13T16:38:01 ***
2021-02-13 16:36:04.028471
```

**Comment by gqqnbig** [comment]
我可以复现此问题。在ssh运行相同命令，运行了一夜，第二天看发现如下情况：
1. putty显示连接已断开
2. out文件显示
```
...
2021-02-15 01:51:29.262868
2021-02-15 01:51:30.263505
slurmstepd-localhost: error: *** STEP 219.0 ON localhost CANCELLED AT 2021-02-15T01:52:09 ***
2021-02-15 01:51:31.2646
```
3.  /var/log/auth.log显示
```
Feb 15 01:52:09 eureka sshd[3478847]: pam_unix(sshd:session): session closed for user qiqig
Feb 15 01:52:09 eureka sshd[3398198]: pam_unix(sshd:session): session closed for user qiqig
Feb 15 01:52:09 eureka systemd-logind[1957]: Session 403 logged out. Waiting for processes to exit.
Feb 15 01:52:09 eureka systemd-logind[1957]: Session 399 logged out. Waiting for processes to exit.
```
![qiqig](https://user-images.githubusercontent.com/614159/107901498-bd742500-6f7e-11eb-91f3-5cbe963ee5c9.png)


你的情况与此类似。/var/log/auth.log.1有
```
Feb 13 16:38:01 eureka sshd[2453084]: pam_unix(sshd:session): session closed for user will
Feb 13 16:38:01 eureka systemd-logind[1957]: Session 329 logged out. Waiting for processes to exit.
```

这说明ssh不稳定，当ssh断开，slurm的程序也终止了。这行为是符合标准的，只要ssh断开，从ssh运行的命令都会停止。

解决方法之一如 https://unix.stackexchange.com/questions/479/keep-processes-running-after-ssh-session-disconnects

但是仔细阅读slurm文档，发现[srun -o](https://slurm.schedmd.com/srun.html)的说明是“By default in interactive mode...”，[FAQ](https://slurm.schedmd.com/faq.html#sbatch_srun)则说到“The srun command is designed for interactive use, with someone monitoring the output.” 既然我们没有坐在电脑前看ssh的输出，就不该用srun，相应地，应该用sbatch。

**Comment by gqqnbig** [comment]
写了一下文档

https://github.com/gqqnbig/mpi-servers/wiki/单服务器（GPU）资源调度#运行一个长期后台作业

请检查一下。

**Comment by wulamao** [comment]
检查过了文档，没有问题。现在重新做测试，测试时间为1天，成功后将关闭该问题。
