### ISSUE TITLE
anaconda environment disappeared

### ISSUE THREAD

**Issue by wulamao** [gqqnbig/mpi-servers#49]
一共发生过两次，一次是用户的虚拟环境消失（可能与当时环境迁移操作有关），另一次是系统安装在/opt下的anaconda消失（在eureka上查看/opt目录确认）。

第二次发生在最近，首先，发现用户目录下的命令重命名文件没有了，快捷命令失效（与第一次现象相同）。然后，进入计算节点没有环境提示 (base) 字样，使用conda命令，提示无法找到 /opt/anaconda3。

原因尚在调查。

**Comment by gqqnbig** [comment]
Eureka `/etc/fstab`有

```
tatooine:/opt   /opt    nfs auto,nofail,noatime,nolock,intr,tcp,actimeo=1800 0 0
```

说明Eureka的/opt由tatooine的/opt提供。

当时可能tatooine关机，所以/opt目录无法挂载。

**Comment by gqqnbig** [comment]
Please close if you are ok with it.

**Comment by wulamao** [comment]
这确实是一个对于第二次现象出现问题的合理解释。但仍与第一次的问题不太相似，这是因为当tatooine处于正常工作状态的时候，第一次出问题的环境并未恢复。
