### ISSUE TITLE
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/mpi-servers#50]
On tatooine

```
$ nvidia-smi
NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.
```

Not sure it's related to #30 .

**Comment by gqqnbig** [comment]
/var/log/apt/history.log.1.gz has

```
Start-Date: 2021-06-04  06:41:09
Commandline: /usr/bin/unattended-upgrade
Upgrade: libnvidia-common-460:amd64 (460.73.01-0ubuntu0.20.04.1, 460.80-0ubuntu0.20.04.2)
End-Date: 2021-06-04  06:41:09
```

似乎6月4日的自动更新覆盖了NVIDIA版本640的驱动，尽管 #30 已经固定了包版本为460。

## 使用apt重新安装
```
$ sudo apt purge '*nvidia-*'
$ sudo ubuntu-drivers autoinstall 
```
完成后nvidia-smi报错“Failed to initialize NVML: Driver/library version mismatch”，但是我用 #30 的方法发现系统只有460版本，不知道哪里mismatch。

## 禁止apt，改回手动安装
Tatooine一开始装机的时候，我就是采用手动安装驱动的方法。

首先`sudo apt purge '*nvidia-*'`删除所有apt管理的驱动，然后手动安装。

结果是成功的。

**Comment by gqqnbig** [comment]
所以我觉得不能让apt管理nvidia包。

有两种办法。一是pin *nvidia-*，设置priority为-1。pin比 #30 的hold似乎更好。二是干脆禁止/usr/bin/unattended-upgrade，我怕它升级别的软件也会不知不觉升坏。

**Comment by wulamao** [comment]
> 所以我觉得不能让apt管理nvidia包。
> 
> 有两种办法。一是`pin *nvidia-*`，设置priority为-1。pin比 #30 的hold似乎更好。二是干脆禁止/usr/bin/unattended-upgrade，我怕它升级别的软件也会不知不觉升坏。

我赞同你的观点，我倾向于第二种方式，即禁止自动更新。

**Comment by gqqnbig** [comment]
已在所有服务器上运行sudo apt remove unattended-upgrades
