### ISSUE TITLE
系统环境未提供CUDA Runtime库

### ISSUE THREAD

**Issue by wulamao** [gqqnbig/mpi-servers#52]
如果有需要的同学，推荐安装自己需要的版本到私人环境内。
如果有方法解决不同CUDA runtime版本（以及g++版本）兼容问题，后续可以考虑在系统中提供相关环境。

**Comment by gqqnbig** [comment]
If it's a tip, please move to wiki.

If you have some action items, please list them.

**Comment by wulamao** [comment]
由于暂时没有人提出下相关需求，此问题将关闭。
