### ISSUE TITLE
[Feature request] higher Slurm version

### ISSUE THREAD

**Issue by Lu-MPI** [gqqnbig/mpi-servers#59]
Server Slurm Version: 19.05
Slurm Doc Version: 21.08

The doc list the --json option,  which is not available on our server.  This is due to the low version of Slurm.

Ubuntu's repository does not yet support higher versions of Slurm, so upgrading Slurm is not easy.

If enough users need the new features of Slurm, then upgrading Slurm will be worthwhile.

**Comment by gqqnbig** [comment]
Which command takes --json?

**Comment by Lu-MPI** [comment]
Wait until the development of the server has stabilised.
