### ISSUE TITLE
Permission error on `conda config --add channels ...`

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/mpi-servers#66]
Unable to run 

conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
conda config --add channels https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/

from https://github.com/gqqnbig/mpi-servers/wiki/%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97

**Comment by Lu-MPI** [comment]
绝大多数用户在Tatooine的 `/home/name/.condarc` 文件来源于
`.condarc -> /home/qiqig/mpi-servers/compute/etc/skel/.condarc`
因此没有修改权限，导致无法添加conda频道。

而在Eureka上，大多数用户没有.condarc文件

用户可以手动删除Tatooine上的.condarc文件来解决这一问题。

**Comment by gqqnbig** [comment]
Can you revise or delete the section on https://github.com/gqqnbig/mpi-servers/wiki/%E7%94%A8%E6%88%B7%E6%8C%87%E5%8D%97 because you wrote it?

**Comment by wulamao** [comment]
> 以手动删除Tatooine上的.condarc文件来解决这一问题。

ok.

**Comment by gqqnbig** [comment]
close the issue when you are done unless you or you want someone to continue working on this case.
