### ISSUE TITLE
[Feature request] LaTeX Support

### ISSUE THREAD

**Issue by Lu-MPI** [gqqnbig/mpi-servers#68]
If the server supports Latex, we can compile the paper on the server.

An option is TeX Live. 

If this is possible, I also recommend installing the latex2html package, which is supported by ubuntu and can compile papers into html.

I have tried installing in the user directory, but due to the limitations of Linux, it is not easy to use the software in this way.

**Comment by gqqnbig** [comment]
How did you install tex live in your home directory? Why is it difficult to use? 

Can you show command lines?

**Comment by Lu-MPI** [comment]
在安装 TexLive时，我没有遇到问题。由于无法使用apt-get进行安装，需要解包并添加环境变量，以运行程序。
在安装 latex2html 时，遇到了问题，由于环境和依赖不正确，程序不能正常运行。

由于apt是系统级而不是用户级的，用户在安装包时步骤变多，还可能失败。我还了解到，当安装的软件有依赖时，用户自行解压安装包并运行不会安装这些依赖。

类似的需求还体现在了部分机器学习库需要从源码编译时，需要使用特定的编译环境。虽然目前可以通过conda和手工配置来解决，但这始终不是便捷的。

**Comment by Lu-MPI** [comment]
基于这些考虑，我尝试用 JuNest 解决问题。

它在用户级沙箱里安装和运行，带有包管理器。类似Conda，使用命令进入和退出所以没有驻留服务或进程。相比于其他的虚拟化方案，JuNest 的开销非常小。 


如果管理员有闲暇，可以评估使用 JuNest 是否是恰当的，和在用户有类似需求又不便于在系统级支持某些特性时，这是否可以作为一种解决方案。

**Comment by gqqnbig** [comment]
要说用户自己安装软件的话，#22  提议安装rootless docker，目前应该已经装在aha上了。

然后装texlive，似乎 https://hub.docker.com/r/texlive/texlive 一句话就能装好。

**Comment by Lu-MPI** [comment]
目前docker好像有权限问题。

我在aha上尝试运行
```
docker pull texlive/texlive
```

报错：
`
Got permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/images/create?fromImage=texlive%2Ftexlive&tag=latest": dial unix /var/run/docker.sock: connect: permission denied
`

另外我看到docker在wiki中是（暂时不考虑）状态，所以就没继续尝试docker了。
