### ISSUE TITLE
如果重启服务器？

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/mpi-servers#7]
如果重启服务器，查看sbatch提交的任务是否还在，查看slurm如何处理正在运行的任务。

**Comment by gqqnbig** [comment]
重启eureka后，

```bash
# sinfo提示eureka down
11:35:26 qiqig@aha:~$ sinfo
PARTITION AVAIL  TIMELIMIT  NODES  STATE NODELIST
normal*      up   infinite      1   down eureka
# 具体原因可以用-R看，发现是Node unexpectedly re(boot)
11:35:28 qiqig@aha:~$ sinfo -R
REASON               USER      TIMESTAMP           NODELIST
Node unexpectedly re root      2021-03-05T11:35:16 eureka
# 这时可以用
sudo scontrol update nodename=eureka state=idle
# 更新节点状态。如果出错slurm_update error: Invalid user id，可以查看/etc/slurm-llnl/slurm.conf，
# 发现SlurmdUser=root
# 所以scontrol update命令要用root运行。
```

**Comment by Lu-MPI** [comment]
机器学习算法通常需要大量GPU时间。
例如，需要14天在M40 GPU上基于ResNet-50模型来训练ImageNet-1k数据集90个epoch。（参考文献 https://arxiv.org/abs/1709.05011）

因此，用户的程序应当有义务保存检查点，以便于服务器维护或意外退出后的继续训练。
目前的最长任务训练时间是3天，这意味着非小型数据集的长期训练必须保存中间结果，并在超时后手动恢复。

基于此，可以讨论：

- 有无必要在任务（异常）结束时及时通知用户（如email，甚至短信）
- 有无必要允许一些任务队列超时或超时自动重启？同时，这些任务也应当接受随时停止以便于服务器维护。甚至随时被挤占。

**Comment by gqqnbig** [comment]
任务重启可以尝试 --dependency 参数 https://slurm.schedmd.com/sbatch.html

**Comment by wulamao** [comment]
sudo systemctl restart nfs-kernel-server sudo mount aha:/home/shared /home/shared

**Comment by gqqnbig** [comment]
sudo scontrol cancel_reboot eureka
scontrol update NodeName="c01" State=undrain Reason="cancelling reboot"

https://groups.google.com/g/slurm-users/c/pXOgpsXWWjA

**Comment by gqqnbig** [comment]
https://unix.stackexchange.com/questions/507589/whats-the-difference-between-nfs-server-and-nfs-kernel-server

nfs-kernel-server is an alias for nfs-server. Maybe beter to stick with `nfs-server`.
