### ISSUE TITLE
Permission error on `conda update conda`

### ISSUE THREAD

**Issue by Lu-MPI** [gqqnbig/mpi-servers#71]
When I update some package in conda, got warning:

```
==> WARNING: A newer version of conda exists. <==
  current version: 4.9.2
  latest version: 4.11.0

Please update conda by running

    $ conda update -n base -c defaults conda
```

When I run `conda update -n base -c defaults conda`
Got permission error:

```
...
Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: failed

EnvironmentNotWritableError: The current user does not have write permissions to the target environment.
  environment location: /opt/anaconda3
  uid: 5002
  gid: 5001

```

这可能需要管理员来更新Conda。
目前的Conda版本是一年前的，新版本的Conda包含了一系列Bug修复： https://docs.conda.io/projects/conda/en/latest/release-notes.html

**Comment by gqqnbig** [comment]
我们没有足够人手来追踪软件更新。比如  #67 已经等待19天了，我们有[45 commits unmerged to master](https://github.com/gqqnbig/mpi-servers/tree/migrate)。

甚至我知道log4j有重大的远程执行漏洞，但没有人手去修复，去修复的话也由于前面的backlog积累，无法很快merge。

所以我们基本上无法执行“因为有更新，所以我们要更新”的策略。

本案中新版本conda有什么功能是你实际（而不是想象中、以后）需要的？当前版本造成了什么问题？

**Comment by Lu-MPI** [comment]
emm……目前没有对新conda的特性需求。

那么目前merge的瓶颈是什么？引入兼职志愿者可以加快这一进程么？

**Comment by gqqnbig** [comment]
如果你没有merge button的话，我会需要两个"looks good to me" (LGTM)令我们merge。

当然有bug的话务必要发现，不要所有PR都直接贴LGTM。

https://github.com/gqqnbig/mpi-servers/blob/469746306beef2b329091db90531fe80f9cb67e8/README.md?plain=1#L6-L10
