### ISSUE TITLE
已对服务器做的操作（coruscant 16，dagobah 17）

### ISSUE THREAD

**Issue by Lu-MPI** [gqqnbig/mpi-servers#74]
服务器到了之后我配置了 coruscant16，dagobah17 两个服务器。

# TLDR:
	coruscant16：手动走完了【GPU服务器安装】的公共配置和安装软件步骤，pytorch测试可以识别GPU，tensorflow还没安装
	dagobah17：TLDR:手动走完了【GPU服务器安装】的公共配置和安装软件步骤，但【没有apt-mark hold nvidia驱动 】，pytorch测试可以识别GPU，tensorflow还没安装

# 操作细节

## coruscant：ip16

按照wiki： https://github.com/gqqnbig/mpi-servers/wiki/GPU服务器安装

中提到的公共配置：https://github.com/gqqnbig/mpi-servers/blob/master/setup.sh

手动执行了：
sudo timedatectl set-timezone Asia/Macau
sudo systemctl isolate multi-user.target 
sudo systemctl set-default multi-user.target

sudo update-grub
sudo apt update
sudo apt upgrade

sudo addgroup wheel
sudo chown :wheel /usr/bin/su
sudo chmod 4754 /usr/bin/su
sudo usermod -aG wheel $(whoami)

sudo systemctl disable motd-news
sudo chmod -x /etc/update-motd.d/50-motd-news
sudo apt-mark hold 'nvidia*'

#### 按照wiki GPU服务器安装 执行命令

sudo apt install -y htop p7zip-full libpam-pwquality

sudo apt install -y ubuntu-drivers-common
sudo ubuntu-drivers autoinstall
sudo reboot  # 重启了

#### 装了conda

wget https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh
chmod +x Anaconda3-2020.11-Linux-x86_64.sh
./Anaconda3-2021.11-Linux-x86_64.sh
安装路径使用了默认的 /home/stu/anaconda3
conda 修改了 /home/stu/.bashrc

按照 https://github.com/Lu-MPI/MPI-Server-Note/wiki/%E9%85%8D%E7%BD%AE%E7%8E%AF%E5%A2%83%28Pytorch%29

配置环境名为lu

安装pytorch

sudo apt install speedtest-cli  #### 打算测试网速，因为下载包比原来慢很多

## dagobah ip17

sudo apt install traceroute

sudo timedatectl set-timezone Asia/Macau
sudo systemctl isolate multi-user.target 
sudo systemctl set-default multi-user.target 

sudo update-grub
sudo apt update
sudo apt upgrade

sudo addgroup wheel
sudo chown :wheel /usr/bin/su
sudo chmod 4754 /usr/bin/su
sudo usermod -aG wheel $(whoami)

sudo systemctl disable motd-news
sudo chmod -x /etc/update-motd.d/50-motd-news

#### 没有禁止变更nvidia驱动  也就是没执行 sudo apt-mark hold 'nvidia*'

sudo apt install -y htop p7zip-full libpam-pwquality

sudo apt install -y ubuntu-drivers-common
sudo ubuntu-drivers autoinstall
sudo reboot # 重启了

#### 装了conda

wget https://repo.anaconda.com/archive/Anaconda3-2021.11-Linux-x86_64.sh
chmod +x Anaconda3-2020.11-Linux-x86_64.sh
./Anaconda3-2021.11-Linux-x86_64.sh
安装路径使用了默认的 /home/stu/anaconda3
conda 修改了 /home/stu/.bashrc

按照 https://github.com/Lu-MPI/MPI-Server-Note/wiki/%E9%85%8D%E7%BD%AE%E7%8E%AF%E5%A2%83%28Pytorch%29

配置环境名为lu

安装pytorch

**Comment by Lu-MPI** [comment]
## 测试 tensorflow 导入时间

之前发现tensorflow在特定的显卡驱动上import需要很长时间（几分钟）

我在 coruscant 上进行测试：
``` bash
>> cat /proc/driver/nvidia/version
NVRM version: NVIDIA UNIX x86_64 Kernel Module  470.86  Tue Oct 26 21:55:45 UTC 2021
```

使用如下脚本测试：
``` bash
wget https://github.com/Lu-MPI/MPI-Server-Note/raw/main/test_tensorflow_import.py
conda activate tf
python test_tensorflow_import.py
```

输出：
```
Try import tensorflow finished in 0.8926 sec
Finding visible devices, CPU and GPU finished in 6.1378 sec
```

时间在可接受范围内。

**Comment by Lu-MPI** [comment]
coruscant  已经完成了 【GPU服务器安装】中的所有步骤，另外两台（17，18）服务器无法连接。

**Comment by gqqnbig** [comment]
```
To install conda's shell functions for easier access, first activate, then:

conda init

If you'd prefer that conda's base environment not be activated on startup,
   set the auto_activate_base parameter to false:

conda config --set auto_activate_base false

Thank you for installing Anaconda3!
./Anaconda3-2021.11-Linux-x86_64.sh: 516: Syntax error: "(" unexpected (expecting ")")
```

你安装anaconda有这个错误吗？

**Comment by Lu-MPI** [comment]
没有 @gqqnbig

**Comment by Lu-MPI** [comment]
看错误的位置，是在额外的一段“Running package tests in a subshell”中，我倾向于认为没有对安装产生影响。

![image](https://user-images.githubusercontent.com/79034835/148347115-48d5a7ad-a1b1-46b3-9079-20796d8c7165.png)

**Comment by gqqnbig** [comment]
在Production site，必须没有错误。我安装Anaconda3-2020.11-Linux-x86_64.sh就没有错。

所以很抱歉无法用最新版本，也进一步拒绝了 #71 。😋

If users are willing to take risks, they can install latest version in their home directory.

**Comment by Lu-MPI** [comment]
可以尝试校验sha或者下载miniconda试试么？

**Comment by Lu-MPI** [comment]
或者安装后conda update 自己？
