### ISSUE TITLE
Try out LDAP

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/mpi-servers#78]
Per #77, please implement LDAP on Synology.

**Comment by wulamao** [comment]
LDAP Server enabled.

**Comment by gqqnbig** [comment]
In your demo, can you show me

1. You create an account on one machine.
2. Then you can use the credential to log in to another machine.

Thanks.

**Comment by wulamao** [comment]
Two test cases will be shown below,
1. create a user account in LDAP Server;
2. delete the accont in LDAP Server.

**Comment by wulamao** [comment]
1. Install LDAP Server on NAS: seach 'LDAP Server' in Package Center and install it.
2. Modify settings (FQDN&Password): 
- https://kb.synology.com/en-br/DSM/help/DirectoryServer/ldap_server?version=6
- https://kb.synology.com/en-us/DSM/help/DSM/AdminCenter/file_directory_service_ldap?version=6
3. Install LDAP Client on other nodes:
- sudo apt-get update
- sudo apt -y install libnss-ldapd libpam-ldapd ldap-utils nslcd (TODO: verify again)
4. Modify settings
- /etc/nsswitch.conf 
- /etc/pam.d/common-password
- /etc/pam.d/common-session
- /etc/nslcd.conf
5. Update conf. & restart service
- sudo service nscd restart (TODO: update)
- sudo service nslcd restart (TODO: update)
6. CMD [`ldapsearch`](http://manpages.ubuntu.com/manpages/focal/en/man1/ldapsearch.1.html) 
7. Test cases: create & delete accout
8. TODO: move to wiki and add details

**Comment by gqqnbig** [comment]
The issue is still in your plate 😋

**Comment by gqqnbig** [comment]
Can you pull off what you have by Friday? Paste what you have in your notebook. If you want to experiment something else, create separate issues.

This is to increate the turnover.

**Comment by wulamao** [comment]
Look at [LDAP-Service-Configuration](https://github.com/gqqnbig/mpi-servers/wiki/LDAP-Service-Configuration).
