### ISSUE TITLE
conda cache packages

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/mpi-servers#8]
Check if https://github.com/conda/conda/issues/7227 is still an issue

**Comment by gqqnbig** [comment]
```
14:59:41 qiqig@aha:/home$ sudo bash -c "find . -type d \( -name backups \) -prune -false -o -path '*/.conda/pkgs' | xargs du -xhd 0"
221M    ./shared/ashlyn/.conda/pkgs
5.3G    ./shared/wayne/.conda/pkgs
9.1G    ./shared/mahan/.conda/pkgs
5.6G    ./shared/qiqig/.conda/pkgs
3.9G    ./shared/helihua/.conda/pkgs
20G     ./shared/wanglu/.conda/pkgs
5.4G    ./shared/summer/.conda/pkgs
```
总共约50G。

**Comment by Lu-MPI** [comment]
按经验看，不同版本的ML库和Cuda Toolkit是缓存比较大的主因。
在新环境配置、验证完毕后，可以使用conda clean --all等命令清理缓存（可以加到用户说明里边，建议用户定期清理）。

**Comment by Lu-MPI** [comment]
## 可以考虑做个内网conda/pip本地镜像

类似清华源（https://mirrors.tuna.tsinghua.edu.cn/help/anaconda/）
但是只提供部分镜像适用于服务器配置的版本，比如较大的包和使用频率高的包

显然的好处：
 缓解网络低速瓶颈，装环境更快，放心的清理缓存。
 刚接触Python的会经常折腾环境，这样可以放心的折腾环境而不必担心重下载慢。

**Comment by Lu-MPI** [comment]
不过做镜像显然是一个优先级较低的工作。

**Comment by gqqnbig** [comment]
in /etc/exports, added
```
/opt/anaconda3/pkgs eureka.ipm.edu.mo(rw,sync,no_subtree_check)
```
/opt/anaconda3/pkgs is conda cache folder, which has 100GB.
