### ISSUE TITLE
[Jan 21] Install dagobah

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/mpi-servers#89]
do on Jan 21.

Proceed up to nvidia-smi. Do not worry about slurm.

**Comment by gqqnbig** [comment]
This should be an opportunity for you to try out zsh, [oh my zsh](https://ohmyz.sh/), and optionally [Powerlevel10k](https://github.com/romkatv/powerlevel10k), a theme for Zsh.

**Comment by gqqnbig** [comment]
Work together with me. Let me know when you are ready to go or you want to change the date.

**Comment by wulamao** [comment]
> 与我一起工作。当您准备好出发或想要更改日期时，请告诉我。

No problem.

**Comment by wulamao** [comment]
naboo 由于GPU问题未安装。今天安装的是dagobah。
目前，已经安装了公共配置以及显卡驱动。

**Comment by gqqnbig** [comment]
https://github.com/gqqnbig/mpi-servers/wiki/%E6%9C%8D%E5%8A%A1%E5%99%A8%E5%AE%89%E8%A3%85/_compare/5f33ddbcfeba78f16a952ddb7b73914246aef7ad...ad0d0d37d2d01aba642c55da669a6666a53e3a60#

```diff
- sudo apt install -y "$arr[@]"
+ sudo apt install -y ${arr[*]}
```
is suspicious .

Assume the name of applications to install has spaces, eg.

```console
$ arr=(
breeze-icon-theme # for partitionmanager
gdebi-core  # for beyond compare
gedit 
ttf-wqy-zenhei
'hello world'  #要装一个名字有空格的软件
)

$ sudo apt install ${arr[*]}
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'fonts-wqy-zenhei' instead of 'ttf-wqy-zenhei'

No apt package "world", but there is a snap with that name.
Try "snap install world"

E: Unable to locate package world
```

I would expect apt to report error like "E: Unable to locate package **hello world**"

As you may know, `cd ~/my documents/` is different than `cd "~/my documents/"`.

I guess you would have to add back the quotes it had, and try the differences between `[*]` and `[@]`.

Since the script is for bash (not zsh), the documentation is at https://www.gnu.org/software/bash/manual/bash.html#Arrays.

If it takes you too much time or there are too subtleties, I will figure it out.

**Comment by wulamao** [comment]
总结如下：
区别Shell 数组中 $arr[\*] and $arr[\@] or "$arr[\*]" and "$arr[\@]" :
1. 不加引号的时候，两者类似；
2. 加引号的时候，\*将变量扩展成1整条字符串，而\@维持了变量的原本结构；
```bash
arr=(
'hello world' # 带空格的 字符串 or 包名称
'others'
)
"$arr[*]"  => 'hello world others ' 
"$arr[@]" => 'hello world'  'others'
```

**Comment by gqqnbig** [comment]
Good job. Thank you!
