### ISSUE TITLE
LDAP with public key authentication

### ISSUE THREAD

**Issue by gqqnbig** [gqqnbig/mpi-servers#91]
Figure out how to create a user in LDAP and allow him to log in with his public key.

**Comment by gqqnbig** [comment]
请把你的发现补充进你的文档。

如果文档里有连续的大于等于10行的命令，把它们变成一个脚本，用PR的方式提交，以便以无人值守的方式运行。脚本放在~/mpi-servers/xxx.sh即可，可以提交多个脚本。

说明文档和脚本尽量以**无脑**方式运行。

新增下一个节点时，会由我来配置LDAP。那个时候我会看你文档，但我不希望口头问你。我会趁你休假的时候配置LDAP，如果你不希望work lift balance被打破，在universal studio玩的时候还要拿出电脑来解释，就尽量把文档写清楚。

**Comment by wulamao** [comment]
OK.
先放2个链接备忘。
https://serverfault.com/questions/653792/ssh-key-authentication-using-ldap
https://serverfault.com/questions/138731/private-key-authentication-with-pam-ldap

**Comment by wulamao** [comment]
> OK.

调研总结：
在 [ssh-key-authentication-using-ldap](https://serverfault.com/questions/653792/ssh-key-authentication-using-ldap) 的问题下，有人提出了一种解决方案。即按插件 [openssh-ldap-publickey](https://github.com/AndriiGrytsenko/openssh-ldap-publickey)扩展OpeSSH来实现密钥验证。

这种方式，貌似是通过在用户对象中添加`sshPublicKey`属性，以便使用 `ldapsearch` 命令来查询验证用户的公钥，从而实现无密码登录。 

要实现该方案，需要在群晖系统中安装此插件，或者实现类似的功能（管理和验证密钥）。
需要注意的是，群晖系统并不内置常见的包管理工具（yum/apg-get/ipkg等），也尚未明确该系统（Linux rs2421 4.4.180+ #42218 SMP Mon Oct 18 19:15:51 CST 2021 x86_64 GNU/Linux synology_v1000_rs2421rp+）与主流系统的差异。
