### ISSUE TITLE
Allow to change shell in LDAP

### ISSUE THREAD

**Issue by wulamao** [gqqnbig/mpi-servers#95]
当我们使用命令 `chsh -s /bin/zsh` 去改变新建用户的默认shell，这个问题会出现。

这个问题与[user-does-not-exist-in-etc-passwd](https://askubuntu.com/questions/348134/user-does-not-exist-in-etc-passwd-when-trying-to-change-the-default-shell) 类似。

**Comment by wulamao** [comment]
这个问题出现的原因，初步判断如下：由于我们使用LDAP作为用户信息管理，因此用户的详细信息并不会出现在本地机器。

**Comment by gqqnbig** [comment]
Error message is 

user 'xxx' does not exist in /etc/passwd

**Comment by gqqnbig** [comment]
The default shell for LDAP user is not even BASH, it is SH, way ancient.

**Comment by gqqnbig** [comment]
https://community.synology.com/enu/forum/17/post/82944
